update scripts and new ones
call: turn on skype and call a number if given
fix_dropbox_icons: fix the white background in system tray
slug: add an option
smowdocker: docker helper
smowmutt: remove cc
smowqemu: parameters tunning
symlink2bin: small fix

diff --git a/call b/call
--- a/call
+++ b/call
@@ -1,4 +1,10 @@
 #!/bin/bash
 
-NUMBER=$(keyring get $1 $USER)
-[ -n "$NUMBER" ] && skype --callto $NUMBER
+NUMBER=$(keyring get call_$1 $USER)
+[ -z "$NUMBER" ] && echo "Contact not found!" && exit 1
+
+if [ -z "$(pgrep -x skype)" ]; then
+	skype &
+	sleep 4
+fi
+skype --callto $NUMBER
