fix dotfiles and smowhome using new scheme

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -26,11 +26,24 @@ setup_git() {
 	echo "    email = $EMAIL" >> $GIT_FILE
 }
 
-[ -h $0 ] && EXEC=$(dirname $0)/$(readlink $0) || EXEC=$0
+
+EXEC=${BASH_SOURCE[0]}
+[ -h $EXEC ] && EXEC="$(dirname $EXEC)/$(readlink $EXEC)"
+
 SCRIPTS_DIR="$(cd $(dirname $EXEC); pwd)"
 
 # I always checkout the dotfiles repo in the same directory as the script one.
 DOTFILES_DIR=${SCRIPTS_DIR/scripts/dotfiles}
+
+SYMLINK_EXEC=symlink2bin
+if ! command -v $SYMLINK_EXEC >/dev/null 2>&1; then
+	if [ -f $SCRIPTS_DIR/$SYMLINK_EXEC ]; then
+		SYMLINK_EXEC="$SCRIPTS_DIR/$SYMLINK_EXEC"
+	else
+		echo "Symlink executable not found!"
+		exit 1
+	fi
+fi
 
 if ! test -d $DOTFILES_DIR; then
 	echo "There is no dotfiles directory. Cloning one..."
@@ -50,9 +63,9 @@ set +f
 case $1 in
 	install|'')
 		initial_dirs
-		symlink2bin -p. $HOME         $DOTFILES_LIST
-		symlink2bin     $HOME/.config $DOTFILES_CONFIG_LIST
 		setup_git
+		$SYMLINK_EXEC -p. $HOME         $DOTFILES_LIST
+		$SYMLINK_EXEC     $HOME/.config $DOTFILES_CONFIG_LIST
 		;;
 
 	clean)
diff --git a/smowhome b/smowhome
--- a/smowhome
+++ b/smowhome
@@ -1,26 +1,7 @@
 #!/bin/bash
 
-if ! command -v realpath >/dev/null 2>&1; then
-	echo"You need to install realpath package!"
-	exit 1
-fi
-
-EXTRA=
-
-create_symlinks() {
+initial_dirs() {
 	mkdir -p ~/bin
-	echo -e "\nCreating symlinks\n-----------------------------------"
-	DIR=$(dirname $(realpath $0))
-
-	# skip "local" scripts
-	[ -n "$(env | grep 'SSH_CLIENT')" ] && EXTRA="-not -iwholename '*local*'"
-
-	for FILE in $(find $DIR -type f -executable -not -iwholename '*.git*' $EXTRA | sort); do
-		FILE=$(echo $FILE | sed "s,${DIR}\/,,g")
-
-		echo "Creating $(basename $FILE) symlink in ~/bin..."
-		ln -fs $DIR/$FILE ~/bin/$(basename $FILE)
-	done
 }
 
 backup() {
@@ -47,6 +28,26 @@ check_private() {
 	fi
 }
 
+if ! command -v realpath >/dev/null 2>&1; then
+	echo"You need to install realpath package!"
+	exit 1
+fi
+
+EXEC=${BASH_SOURCE[0]}
+[ -h $EXEC ] && EXEC="$(dirname $EXEC)/$(readlink $EXEC)"
+
+SCRIPTS_DIR="$(cd $(dirname $EXEC); pwd)"
+
+SYMLINK_EXEC=symlink2bin
+if ! command -v $SYMLINK_EXEC >/dev/null 2>&1; then
+	if [ -f $SCRIPTS_DIR/$SYMLINK_EXEC ]; then
+		SYMLINK_EXEC="$SCRIPTS_DIR/$SYMLINK_EXEC"
+	else
+		echo "Symlink executable not found!"
+		exit 1
+	fi
+fi
+
 case $1 in
 
 	backup)
@@ -54,7 +55,9 @@ case $1 in
 		;;
 
 	*)
-		create_symlinks
+		$SCRIPTS_DIR/dotfiles
+		$SYMLINK_EXEC ~/bin $(find $SCRIPTS_DIR -maxdepth 1 -mindepth 1 -executable -type f)
+		$SYMLINK_EXEC ~/bin $SCRIPTS_DIR/smartprompt
 		;;
 esac
 
