symlink now erase symlinks before copy it

diff --git a/symlink2bin b/symlink2bin
--- a/symlink2bin
+++ b/symlink2bin
@@ -1,21 +1,28 @@
 #!/bin/bash
 
-[ -n "$1" ] && DIR=$1 || DIR=$PWD
-[ ! -d "$DIR" ] && echo "$DIR not found!" && exit 1
+[ -n "$1" ] && SOURCE=$1 || SOURCE=$PWD
+[ -n "$2" ] && DEST=$1 || DEST=~/bin
+[ ! -d "$SOURCE" ] && echo "$SOURCE not found!" && exit 1
 
 set -o noglob
 
 FIND_PARAM='-type f -executable -not -iwholename '*.git*''
 env | grep -q SSH_CLIENT && FIND_EXTRA='-not -iwholename '*local*''
 
-mkdir -p ~/bin
-cd $DIR
+if [ -d $DEST ]; then
+	cd $DEST
+	FILES=$(ls -l | grep "$SOURCE" | awk '{ print $9 }')
+	[ -n "$FILES" ] && rm $FILES
+else
+	mkdir $DEST
+fi
 
-for FILE in $(find $DIR $FIND_PARAM $FIND_EXTRA | sort); do
-	FILE=$(echo $FILE | sed "s,${DIR}\/,,g")
+cd $SOURCE
+for FILE in $(find $SOURCE $FIND_PARAM $FIND_EXTRA | sort); do
+	FILE=$(echo $FILE | sed "s,${SOURCE}\/,,g")
 
-	echo "Creating $(basename $FILE) symlink in ~/bin..."
-	ln -fs $DIR/$FILE ~/bin/$(basename $FILE)
+	echo "Creating $(basename $FILE) symlink in ${DEST}..."
+	ln -fs $SOURCE/$FILE $DEST/$(basename $FILE)
 done
 
 set +o noglob
